<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39221" started-at="2019-04-20T06:53:49Z" finished-at="2019-04-20T06:54:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39221" started-at="2019-04-20T06:53:49Z" finished-at="2019-04-20T06:54:28Z">
      <class name="tests.TC_001">
        <test-method status="PASS" signature="setUpTest()[pri:0, instance:tests.TC_001@4b9e13df]" name="setUpTest" is-config="true" duration-ms="10362" started-at="2019-04-20T06:53:49Z" finished-at="2019-04-20T06:53:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="SearchProperties()[pri:0, instance:tests.TC_001@4b9e13df]" name="SearchProperties" duration-ms="15816" started-at="2019-04-20T06:53:59Z" finished-at="2019-04-20T06:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchProperties -->
        <test-method status="PASS" signature="printPropertyPrices()[pri:2, instance:tests.TC_001@4b9e13df]" name="printPropertyPrices" duration-ms="5972" started-at="2019-04-20T06:54:15Z" finished-at="2019-04-20T06:54:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printPropertyPrices -->
        <test-method status="PASS" signature="checkAgent()[pri:3, instance:tests.TC_001@4b9e13df]" name="checkAgent" duration-ms="6870" started-at="2019-04-20T06:54:21Z" finished-at="2019-04-20T06:54:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkAgent -->
        <test-method status="FAIL" signature="verifyAgent()[pri:4, instance:tests.TC_001@4b9e13df]" name="verifyAgent" duration-ms="153" started-at="2019-04-20T06:54:28Z" finished-at="2019-04-20T06:54:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Balgores] but found [Balgores, RM14]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Balgores] but found [Balgores, RM14]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.agentPage.verifyAgentName(agentPage.java:15)
at tests.TC_001.verifyAgent(TC_001.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAgent -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:tests.TC_001@4b9e13df]" name="tearDownTest" is-config="true" duration-ms="0" started-at="2019-04-20T06:54:28Z" finished-at="2019-04-20T06:54:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
      </class> <!-- tests.TC_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
